### ISSUE TITLE
egybest-cli.py -url 'https://www.egybest.org/movie/top-five-2014'

### ISSUE THREAD

**Issue by ayoubelmhamdi** [SafwanLjd/EgyBestCLI#3]
could you please add the option to download from URL directoment  
now I am trying to use some `cli` like `curl` to get the name and `session` and `episode`

**Comment by SafwanLjd** [comment]
That's not a bad idea… But why would you want this feature?… you'd have to go to the actual website and copy the link of the movie/show every time…

If I have the time I will gladly add this feature, but for now you can use some other command like:

```bash
egybest --title "$(echo 'https://www.egybest.org/movie/top-five-2014' | cut -d/ -f5 | tr '-' ' ')"
```

**Comment by ayoubelmhamdi** [comment]
I'm using the `termux` on my phone  
when I found a URL useful to download I download it, from `TikTok` or `Facebook` or `Youtube` ...
thank's to you, now I can download also `egybest` 

now I use this `script to wrap your cli`
<details>

```bash
#!/bin/bash

url=${1:-}


if [[ -z $url ]];then
    echo
    echo 'download the egybest url'
    echo
else
    gender="$(echo $url | awk -F "/" '{print $4}')"
    title="$(echo $url | awk -F "/" '{print $5}')"

    name="$(echo $title | perl -pe 's#-season-\d+-ep-\d+##;s#-# #g')"
    if [[ $gender == "episode" ]];then
        season="$(echo $title | perl -pe 's#^.*?-season-(\d+).*#\1#')"
        ep="$(echo $title | perl -pe 's#^.*?-season-\d+-ep-(\d+).*#\1#')"
        egybest-cli.py --title "\"$name\"" -S "$season" -E "$ep"
    elif [[ $gender == "movie" ]];then
        egybest-cli.py --title "\"$name\""
    else
        echo "$gender = not in [episode, movie]"
    fi
fi
```
</details>

**Comment by ayoubelmhamdi** [comment]
there is also diff between the movies and `series`

**Comment by SafwanLjd** [comment]
This project has been officially discontinued, so I'm going to close this issue.
